# site settings
title: Leo
subtitle: Alchieri
email: leo.alchieri@me.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: ""# the base hostname & protocol for your site
author: "Leonardo Alchieri"
# street_address:
city: "Near Milan ðŸ¤—"
#state:
#zip_code:
#country:
phone: "Ask me! ðŸ˜„"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/LeonardoAlchieri
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/leo_alchieri/
linkedin_url: https://www.linkedin.com/in/leonardo-alchieri-7b556a16b/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
